### PR TITLE
fix: skip unknown denoms (execute swap)

### LINKED ISSUE #62: [BUG] update_global_index fails if anchor_basset_reward has denoms with no exchange rate available
**Describe the bug**
The `update_global_index` handler fails if there are tokens with unknown exchange rates  on the `anchor_basset_reward` contract balance:

```{"error":"rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: dispatch: dispatch: ibc/0471F1C4E7AFD3F07702BEF6DC365268D64570F7C1FDC98EA6098DD6DE59817B: no price registered with oracle: invalid request"}```

**To Reproduce**
For the current mainnet: send any IBC token to the reward contract and try to execute `update_global_index`. 

**Context & versions**
0.2.0
0.1.0

**(if applicable) suggested solution**
The solution is to handle only the tokens with known exchange rates.

### PR DESCRIPTION
**Pull request by zavgorodnii**
## Summary of changes

<Describe summary of major changes here>
Fixes #62 

## Report of required housekeeping

- [x] Github issue OR spec proposal link
- [x] Wrote tests
- [x] Added a relevant changelog entry to CHANGELOG.md

----

## (FOR ADMIN) Before merging

- [x] Added appropriate labels to PR
- [x] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [x] Confirm added tests are consistent with the intended behavior of changes
- [x] Ensure all tests pass

### CODE REVIEW

File: contracts/anchor_basset_reward/src/global.rs [hunk 1]
```diff
@@ -9,6 +9,7 @@ use terra_cosmwasm::{create_swap_msg, ExchangeRatesResponse, TerraMsgWrapper, Te
 /// Swap all native tokens to reward_denom
```
Comment (MSNTCS) [inline contracts/anchor_basset_reward/src/global.rs:9]: Please add migrate handle to the `contract` file.

**Review by MSNTCS — CHANGES_REQUESTED** [review]

**Review by MSNTCS — APPROVED** [review]
